name: second custom workflow

on: [push]

jobs:
    job1:
        name: first job
        runs-on: ubuntu-latest
        steps:
            - name: job 1 - step 1
            - run: echo date

    job2:
        name: first job
        runs-on: windows-latest
        steps:
            - name: job 1 - step 2
            - run: Get-Date

    job3:
        name: first job
        runs-on: macos-latest
        steps:
            - name: job 1 - step 3
            - run: echo date

    job4:
        job1:
        name: first job
        runs-on: ubuntu-latest
        needs: [job1, job, job3]
        steps:
            - name: job 1 - step 4
            - run: echo date
