name: second custom workflow

on: [push]

jobs:
    job1:
        name: first job (ubuntu)
        runs-on: ubuntu-latest
        steps:
            - name: job 1 - step 1
              run: echo date

    job2:
        name: first job (windows)
        runs-on: windows-latest
        steps:
            - name: job 2 - step 1
              run: Get-Date

    job3:
        name: first job (macos)
        runs-on: macos-latest
        steps:
            - name: job 3 - step 1
              run: echo date

    job4:
        name: first job (final)
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: job 4 - step 1
              run: echo date
